### ISSUE TITLE
library not found for -lCcmark for architecture x86_64

### ISSUE THREAD

**Issue by wesleysui** [IBM-Swift/Kitura-Sample-iOS#2]
I am trying to build this sample project with Xcode9, but it seems something wrong with the framework **lCcmark**

**Comment by vadimeisenbergibm** [comment]
@wesleysui I did not yet work on Kitura/iOS for Swift 4 and Xcode 9, will work on it by 16-th of October.

**Comment by vadimeisenbergibm** [comment]
@wesleysui I have updated the project to iOS 11, Swift 4 and Xcode 9. 
Note that the travis build passes. I tested on iPhone 7 with iOS 11, it works for me, as well on a Simulator with iPhone 8.

Please try and let me know. Please provide the details of your mac OS, iOS, and device version, in case it does not work.

**Comment by wesleysui** [comment]
@vadimeisenbergibm it works on my side with Mac OS 10.13, iOS 11 on iPhone 8p.
thanks.
